export default function AboutPage() {
  return <main className="article-page">
    <header className="site-header"><a className="brand" href="/">Julian Wortelboer</a><nav aria-label="Primary navigation"><a href="/insights">Insights</a><a href="/contact">Work with Julian</a></nav></header>
    <article><header className="article-header"><p className="eyebrow">Club development · Operations · Coach education</p><h1>About Julian Wortelboer</h1><p>Padel club consultant, operator and Master Coach.</p></header>
    <div className="article-body" style={{maxWidth: '850px', margin: '0 auto', padding: '0 24px 64px'}}>
      <p>For more than 25 years, I have run padel and racquet clubs, developed programs and helped coaches and teams improve. My consulting work brings together club development, daily operations, programming and leadership.</p>
      <h2>Experience inside the club</h2><p>My experience includes Chief Padel Officer and Club & Program Developer at Ultra Padel Club, Club Consultant & Developer at Unico Club in Weston, Program Director & Academy Developer at Wynwood Padel Club, and Club Consultant & Program Developer at Padel Club Maracaibo, Venezuela. I have also served as Director of Racquet Sports at The Ocean Club in Key Biscayne.</p><p><a href="/#work">Explore my selected club work</a>, including ICON Padel Club and Park Padel.</p>
      <h2>Developing coaches and sharing knowledge</h2><p>As a Padel Smash Academy co-founder, I work on coach education and certification. My book, Mastering the Art of Coaching Padel, shares a methodology for developing players, empowering coaches and growing the sport.</p><p><a href="https://www.padelsmashacademy.com/products/courses/padelcoachcertficiation">Explore Padel Smash Academy coach certification</a> or <a href="https://www.amazon.com/MASTERING-ART-COACHING-PADEL-Methodology-ebook/dp/B0H8R4336Q/">view my coaching book</a>.</p>
      <h2>The Complete Padel Club Blueprint</h2><p>I developed the Blueprint as a comprehensive operating manual provided to consulting clients—covering pre-opening, launch, daily operations, programming, and scalable growth.</p>
      <h2>Ideas from the court and the business</h2><p>My <a href="/insights">Insights articles</a> cover club strategy and operations, coaching and player development, and padel industry leadership. I also share padel education through <a href="https://www.youtube.com/@padelsmashtv">Padel Smash TV</a>.</p>
      <h2>Work with me</h2><p>Based in Miami and available for select projects worldwide, I help investors and operators build stronger padel clubs and coaching programs. <a href="/contact">Contact Julian about your project</a>.</p><p><a href="https://www.linkedin.com/in/julianwortelboer">LinkedIn</a> · <a href="https://www.instagram.com/julianwortelboer/">Instagram</a></p>
    </div></article></main>;
}
